//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKLC_Transfers
    {
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> DeleteSTS { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUser { get; set; }
    
        public virtual ZKLC_CustomerCards ZKLC_CustomerCards { get; set; }
        public virtual ZKLC_Customers ZKLC_Customers { get; set; }
    }
}
