//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKLC_CustomerCards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZKLC_CustomerCards()
        {
            this.ZKLC_Transfers = new HashSet<ZKLC_Transfers>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string CardNo { get; set; }
        public string SecretCode { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Blocked { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
        public string BlockUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUser { get; set; }
    
        public virtual ZKLC_Customers ZKLC_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZKLC_Transfers> ZKLC_Transfers { get; set; }
    }
}
