//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZKLC_RequestLogs
    {
        public int ID { get; set; }
        public string CardN { get; set; }
        public string FIO { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Description { get; set; }
        public string rUrl { get; set; }
        public string rIP { get; set; }
    }
}
